version: "3.9"

services:
  app:
    build: .
    container_name: mvc_biblioteca_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mvc_biblioteca_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      TEMPLATES_DIR: /app/app/templates
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: mvc_biblioteca_db
    environment:
      POSTGRES_DB: mvc_biblioteca_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data       # usa volume nomeado declarado abaixo
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mvc_biblioteca_db"]
      interval: 5s
      timeout: 5s
      retries: 10


# >>> DECLARAÇÃO DO VOLUME (nível raiz) <<<
volumes:
  pgdata:
